name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean -DskipTests verify

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run TestRunner main class
        run: |
          java -cp target/your-artifact-id-1.0-SNAPSHOT.jar RunSurveys.TestRunner1
