name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean -DskipTests verify
        
      - name: Run TestRunner main class
        run: |
          cd /home/runner/work/deap4/deap4
          mvn exec:java -Dexec.mainClass="RunSurveys.TestRunner1"
